[colors]

foreground = "#adbcbc"
background = "#103c48"
ansi = [
    "#174956",
    "#fa5750",
    "#75b938",
    "#dbb32d",
    "#4695f7",
    "#f275be",
    "#41c7b9",
    "#72898f",
]
brights = [
    "#325b66",
    "#ff665c",
    "#84c747",
    "#ebc13d",
    "#58a3ff",
    "#ff84cd",
    "#53d6c7",
    "#cad8d9",
]

cursor_fg = "#103c48"
cursor_bg = "#cad8d9"
cursor_border = "#cad8d9"
compose_cursor = "#ed8649"

selection_fg = "none"
selection_bg = "rgba(50 91 102 62.5%)"
